# Generated by Django 3.2.12 on 2024-05-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_user_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
